#!/usr/bin/env bash
set -euo pipefail

# Install dependencies script
# Must be executed as root
if [[ $UID != 0 ]]; then
    echo "pocketsmith-tg-bot must be started as root"
    echo "Please re-run this script as"
    echo "  sudo ./start"
    exit 1
fi

# Install system dependencies
echo "Installing system dependencies"
if ! yum install -y python3.11 pip3 certbot > /dev/null 2>&1; then 
    echo "An error has ocurred when installing system dependencies"
    exit 1
fi

# Install python modules
echo "Installing python modules"
if ! pip3.11 install requests pyTelegramBotAPI python-telegram-bot-calendar flask gevent.pywsgi toml > /dev/null 2>&1; then
    echo "An error has ocurred when installing python modules"
    exit 1
fi

# Download bot software
cd ~
mkdir pocketsmith-tg-bot
repos=`curl -s https://api.github.com/repos/notleanbarba/pocketsmith-tg-bot/releases/latest`
if [[ $repos =~ "\"message\": \"Not Found\"" ]]; then
    echo "Falling back to default release"
    wget -O - -q https://github.com/notleanbarba/pocketsmith-tg-bot/archive/refs/tags/v-1.0.0-alpha.tar.gz | \
    tar -xz -C ~/pocketsmith-tg-bot/ --strip-components=1
else
    echo "Getting latest release"
    curl -s https://api.github.com/repos/notleanbarba/pocketsmith-tg-bot/releases/latest | \
    grep "tarball_url" | \
    head -1 | \
    cut -d " " -f 4,4 | \
    tr -d \" | tr -d , | \
    wget -q -i - -O - | \
    tar -xzf - -C ~/pocketsmith-tg-bot/ --strip-components=1
fi

cd ~/pocketsmith-tg-bot/
chmod +x ./start
echo "Starting bot"
./start